[package]
name = "tus"
version = "0.1.0"
authors = ["Richo Healey <richo@stripe.com>"]
description = "rust implementation of TUS"
license = "MIT"

[dependencies]
reqwest = "0.9"
failure = "0.1.2"
lazy_static = "1.1.0"
